version: '3'

services:
  app:
    build: ./app
    container_name: 'split-the-bill-app'
    volumes:
      - ./export:/export
    links:
      - db:mongodb
    depends_on:
      - db
  db:
    image: mongo:4.2
    container_name: 'split-the-bill-db'
    volumes:
        - ./mongo-volumes:/data/db
    ports:
      - 27017:27017
